const FETCH_COMPLETE = 1;
const SET_LOADING = 2;
const INPUT_VENDOR = 3;
const SUBMIT_VENDOR = 4;
const IMAGE_VENDOR = 5;
const EDIT_VENDOR = 6;
const DELETE_VENDOR = 7;
const UPDATE_VENDOR = 8;


export {
    SET_LOADING, FETCH_COMPLETE,
    INPUT_VENDOR, SUBMIT_VENDOR, IMAGE_VENDOR,
    EDIT_VENDOR, DELETE_VENDOR, UPDATE_VENDOR,

};
